# Generated by Django 5.1.4 on 2024-12-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=40)),
                ('actor', models.CharField(db_index=True, max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('payload', models.TextField(default='')),
            ],
            options={
                'ordering': ['-created_on'],
                'abstract': False,
            },
        ),
    ]
